extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:testing-library/dom
  - plugin:jest-dom/recommended
env:
  browser: true
  es2020: true
  jest: true
  node: true
plugins:
  - prettier
  - testing-library
  - jest-dom
rules:
  prettier/prettier: error
  # some fals-positives:
  # /home/damien/dev/perso/melodie/common/core/lib/models/abstract-model.test.js
  #   314:38  error  `getById` query is sync so it does not need to be awaited
  testing-library/no-await-sync-query: off
parserOptions:
  ecmaVersion: 11
  sourceType: module
