extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:testing-library/recommended
  - plugin:jest-dom/recommended
env:
  browser: true
  es2020: true
  jest: true
  node: true
plugins:
  - prettier
  - testing-library
  - jest-dom
rules:
  prettier/prettier: error
parserOptions:
  ecmaVersion: 11
  sourceType: module
