name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run Core tests
        run: npm run test:core
        env:
          AUDIODB_KEY: ${{ secrets.AUDIODB_KEY }}

      - name: Run UI tests
        run: npm run test:ui

      - name: Run Desktop tests
        run: npm run test:desktop

      - name: Run Site tests
        run: npm run test:site

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/desktop/coverage/clover.xml,apps/site/coverage/clover.xml,common/core/coverage/clover.xml,common/ui/coverage/clover.xml
