name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js ${{ matrix.node-version }} up
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run UI tests
        run: |
          cd common/ui
          npm test

      - name: Run Core tests
        run: |
          cd common/core
          npm test
        env:
          AUDIODB_KEY: ${{ secrets.AUDIODB_KEY }}

      - name: Run Desktop tests
        run: |
          cd apps/desktop
          npm test

      - name: Run Site tests
        run: |
          cd apps/site
          npm test

      - name: Send coverage to Codacy
        if: always()
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/desktop/coverage/clover.xml,apps/site/coverage/clover.xml,common/core/coverage/clover.xml,common/ui/coverage/clover.xml
