name: release

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: [CI]
    branches: [main]
    types:
      - completed

defaults:
  run:
    working-directory: ./

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flags: l
          - os: windows-latest
            flags: w
          - os: macos-latest
            flags: m

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js up
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm -w common/ui run build

      - name: Release application
        run: npm -w apps/desktop run release:publish -- onTagOrDraft -${{ matrix.flags}}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USE_HARD_LINKS: false

  release-site:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check code out
        uses: actions/checkout@v2

      - name: Set Node.js up
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm -w apps/site run build

      - name: Publish site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/site/build
