name: release

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            flags: l
          - os: windows-latest
            flags: w
          - os: macos-latest
            flags: m

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build:svelte
      - run: npm run release:publish -- onTagOrDraft -${{ matrix.flags}}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
